# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12d4a092fee49af7f7d96e91fd3d8068fbb2edafdb65cd6104360c8d876769a0ca702a370bd7c5533be8f705335e288f64a6b978ac7fb8c7e5cb2c792d1a3d6f

test:
  secret_key_base: 3934e2701d2bfe09e95f920cbeacf9ba4a0e204c3c83ccd340a64f060374ed1dea142456460e8dfeae2825b1ba2141519a89c9fe218f28f0b7b96fac41810244

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
